
export enum ValidateProfileError {
  INCORRECT_USER_DATE = 'INCORRECT_USER_DATE',
  INCORRECT_AGE = 'INCORRECT_AGE',
  INCORRECT_COUNTRY = 'INCORRECT_COUNTRY',
  NO_DATA = 'NO_DATA',
  SERVER_ERROR = 'SERVER_ERROR'
}
